### ISSUE TITLE
Añador la referencia 

### ISSUE THREAD

**Issue by robertoalvarezm** [Fa-Moe/DGBD#10]
En la documentación y ayuda de funciones añadir el paper.
 @article{mansilla2007behavior,
  title={On the behavior of journal impact factor rank-order distribution},
  author={Mansilla, Ricardo and K{\"o}ppen, Elke and Cocho, Germinal and Miramontes, Pedro},
  journal={Journal of informetrics},
  volume={1},
  number={2},
  pages={155--160},
  year={2007},
  publisher={Elsevier}
}

que fue en donde se usó por primera vez esta distribución

**Comment by Fa-Moe** [comment]
Añadido.
