### ISSUE TITLE
Implement new function

### ISSUE THREAD

**Issue by robertoalvarezm** [Fa-Moe/DGBD#13]
En 

@article{fontanelli2022beta,
  title={Beta rank function: A smooth double-Pareto-like distribution},
  author={Fontanelli, Oscar and Miramontes, Pedro and Mansilla, Ricardo and Cocho, Germinal and Li, Wentian},
  journal={Communications in Statistics-Theory and Methods},
  volume={51},
  number={11},
  pages={3645--3668},
  year={2022},
  publisher={Taylor \& Francis}
}

encuentran una forma de generar números aleatorios distribuidos con la Beta-Cocho con parámetros arbitrarios pero fijos. Primero es una forma de tener esa función disponible y segundo es buena  manera para para probar qué tan bueno son los métodos de ajuste.

Acá dejo el código adaptado de ese paper ya en forma de función

BC_random<-function(A=1,a,b,n){
  u<-runif(n)
  return(A*(1-u)^b/u^a)
}

**Comment by Fa-Moe** [comment]
Se añadió una generalización en BC_random().
