### ISSUE TITLE
Gráficas

### ISSUE THREAD

**Issue by robertoalvarezm** [Fa-Moe/DGBD#3]
1.  Poder mover la ubicación de la leyenda. A veces estorba para ver los datos
2. Poder cambiar la escala a log-log
3. Poder cambiarle el fondo a blanco

**Comment by Fa-Moe** [comment]
Se añadireron los argumentos gfx_theme, gfx_xy_trans y gfx_label_coords a la función BC_plot().
-Added the gfx_theme, gfx_xy_trans and gfx_label arguments to the BC_plot() function.
