### ISSUE TITLE
Orden incorrecto de los autores y falta el guión entre los apellidos

### ISSUE THREAD

**Issue by robertoalvarezm** [Fa-Moe/DGBD#5]
En citation(package="DGBD") aparece el orden incorrecto de los autores y sin el guión medio:

Aparece: Alvarez Martinez R, Moedano Vargas F (2024) 
debe ser: Moedano-Vargas F, Alvarez-Martinez Roberto (2024)
 
Tú eres primer autor.
Lo mismo en la entrada Latex

Aparece: author = {Roberto {Alvarez Martinez} and Francisco Farell {Moedano Vargas}},
debe ser: author = {Francisco Farell {Moedano-Vargas} and  Roberto {Alvarez-Martinez} }
 igual, tu eres primer autor y  los apellidos van con guion entre ellos.

**Comment by Fa-Moe** [comment]
Gracias por arreglarlo en el commit 4e94f47.
