### ISSUE TITLE
Falta el manual en pdf

### ISSUE THREAD

**Issue by robertoalvarezm** [Fa-Moe/DGBD#6]
El manual se puede generar automáticamente con la librería devtools

library(devtools)
build_manual(pkg = ".", path = NULL)

Solo debe ir en la carpeta correcta para que pueda ser accesible desde la ayuda en en RStudio

**Comment by Fa-Moe** [comment]
Añadido en /vignettes, no encontré ahora mismo el path correcto.

**Comment by Fa-Moe** [comment]
Cambiado a inst/manual
